# Copyright (C) 2018-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2018-present Sven Greb <development@svengreb.de>
#
# Project:    Nord Docs
# Repository: https://github.com/arcticicestudio/nord-docs
# License:    MIT

# Configuration for Codecov.
#
# References:
# - https://docs.codecov.io/docs/codecov-yaml
# - https://docs.codecov.io/docs/node

codecov:
  branch: master

parsers:
  javascript:
    enable_partials: yes
