# Copyright (C) 2018-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2018-present Sven Greb <development@svengreb.de>
#
# Project:    Nord Docs
# Repository: https://github.com/arcticicestudio/nord-docs
# License:    MIT

# Configuration for SVGO.
#
# References:
# - https://github.com/svg/svgo
# - https://github.com/svg/svgo/blob/master/.svgo.yml

multipass: true
js2svg:
  pretty: true
  indent: 2
