# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

# Configuration for SVGO.
# References:
#   1. https://github.com/svg/svgo

multipass: true
js2svg:
  pretty: true
  indent: 2
